#mybatis配置
mybatis:
  type-aliases-package: com.dunera.seckill.pojo
  configLocation: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mappings/*.xml
#spring-boot配置
spring:
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 5120MB #上传文件,单个文件最大5GB
      max-request-size: 5120MB #上传文件,单次提交总和最大5GB
  output:
    ansi:
      enabled: ALWAYS
  datasource: #数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myseckill?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: lian$lyx9
    name: master
    druid:
      initial-size: 50 #初始化时建立物理连接的个数
      min-idle: 50 #最小连接池数量
      max-active: 200 #最大连接池数量
      max-wait: 1200 #获取连接时最大等待时间，单位毫秒
      pool-prepared-statements: false #PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
      validation-query: SELECT 1
      validation-query-timeout: 3
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      time-between-eviction-runs-millis: 60000 #test-while-idle的判断依据
      min-evictable-idle-time-millis: 30000 #连接保持空闲而不被驱逐的最小时间
      async-close-connection-enable: true
      filters: stat,wall,slf4j
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
          db-type: mysql
  redis: #redis 配置
    database: 8
    host: 127.0.0.1
    password: 123456
    jedis:
      pool:
        max-idle: 10
        min-idle: 10

  session: #session使用redis存储
    store-type: redis
server:
  port: 8081
logging:
  level:
    com.dunera.seckill: DEBUG
